drop table animal_ins;
CREATE TABLE ANIMAL_INS (
	ANIMAL_ID		  VARCHAR(20) NOT NULL,
    ANIMAL_TYPE		  VARCHAR(10) NOT NULL,
    DATETIME		  DATETIME	NOT NULL,
    INTAKE_CONDITION  VARCHAR(10) NOT NULL,
    NAME			  VARCHAR(50),
    SEX_UPON_INTAKE   VARCHAR(100)
);

INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE)
VALUES
('A352713', 'Cat', '2017-04-13 16:29:00', 'Normal', 'Gia', 'Spayed Female'),
('A350375', 'Cat', '2017-03-06 15:01:00', 'Normal', 'Meo', 'Neutered Male');

drop table ANIMAL_OUTS;
CREATE TABLE ANIMAL_OUTS (
	ANIMAL_ID		  VARCHAR(20) NOT NULL,
    ANIMAL_TYPE		  VARCHAR(10) NOT NULL,
    DATETIME		  DATETIME	NOT NULL,
    NAME			  VARCHAR(50),
    SEX_UPON_INTAKE   VARCHAR(100)
);

INSERT INTO ANIMAL_OUTS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_INTAKE)
VALUES
('A349733', 'Dog', '2017-09-27 19:09:00', 'Allie', 'Spayed Female'),
('A352713', 'Cat', '2017-04-25 12:25:00', 'Gia', 'Spayed Female'),
('A349990', 'Cat', '2018-02-02 14:18:00', 'Spice', 'Spayed Female');

SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS AS A RIGHT OUTER JOIN
	ANIMAL_OUTS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID;


SELECT *
FROM ANIMAL_OUTS;