CREATE TABLE id (
	id	LONG NOT NULL PRIMARY KEY,
	name	VARCHAR(50)	NOT NULL,
	address VARCHAR(255) NOT NULL
    
);

CREATE TABLE Orders(
	id	LONG NOT NULL PRIMARY KEY,
	total	DOUBLE	NOT NULL,
	create_at TIMESTAMP NOT NULL,
	FOREIGN KEY(id2) REFERENCES id(id)
);